name: Build and deploy to firebase
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install deps
        run: npm install
      - name: build
        run: npm run build
      - name: deploy to firebase
        uses: w9jds/firebase-action@v2.2.2
        with: 
          args: deploy --only hosting
        env:
         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
